# redis-server.yml
version: '3.7'
services:
    redis:
      image: redis:alpine
      container_name: redis-container
      hostname: redis_boot
      restart: always
      labels:
        - "name=redis"
        - "mode=standalone"
      ports:
        - 6379:6379
      volumes:
        - ./data/:/data
        - ./conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
      env_file:
        - ./.env
      command: >
        sh -c "redis-server --port 6379
              --requirepass ${REDIS_PASSWORD}
              --save 900 1
              --save 300 10
              --save 60 10000
              --dbfilename dump.rdb
              --appendonly yes
              --appendfilename appendonly.aof
              --appendfsync everysec
              --auto-aof-rewrite-percentage 100
              --auto-aof-rewrite-min-size 64mb"